/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DailyRouteImport } from './routes/daily'
import { Route as RemindersRouteImport } from './routes/reminders'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ExamIndexRouteImport } from './routes/exam/index'
import { Route as ExamQuizRouteImport } from './routes/exam/quiz'
import { Route as LawsIndexRouteImport } from './routes/laws/index'
import { Route as LawsLawIdRouteImport } from './routes/laws/$lawId'
import { Route as ReadLawIdNRouteImport } from './routes/read.$lawId.$n'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyRoute = DailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersRoute = RemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamIndexRoute = ExamIndexRouteImport.update({
  id: '/exam/',
  path: '/exam/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamQuizRoute = ExamQuizRouteImport.update({
  id: '/exam/quiz',
  path: '/exam/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const LawsIndexRoute = LawsIndexRouteImport.update({
  id: '/laws/',
  path: '/laws/',
  getParentRoute: () => rootRouteImport,
} as any)
const LawsLawIdRoute = LawsLawIdRouteImport.update({
  id: '/laws/$lawId',
  path: '/laws/$lawId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadLawIdNRoute = ReadLawIdNRouteImport.update({
  id: '/read/$lawId/$n',
  path: '/read/$lawId/$n',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/daily': typeof DailyRoute
  '/reminders': typeof RemindersRoute
  '/search': typeof SearchRoute
  '/exam/quiz': typeof ExamQuizRoute
  '/laws/$lawId': typeof LawsLawIdRoute
  '/exam/': typeof ExamIndexRoute
  '/laws/': typeof LawsIndexRoute
  '/read/$lawId/$n': typeof ReadLawIdNRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/daily': typeof DailyRoute
  '/reminders': typeof RemindersRoute
  '/search': typeof SearchRoute
  '/exam/quiz': typeof ExamQuizRoute
  '/laws/$lawId': typeof LawsLawIdRoute
  '/exam': typeof ExamIndexRoute
  '/laws': typeof LawsIndexRoute
  '/read/$lawId/$n': typeof ReadLawIdNRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/daily': typeof DailyRoute
  '/reminders': typeof RemindersRoute
  '/search': typeof SearchRoute
  '/exam/quiz': typeof ExamQuizRoute
  '/laws/$lawId': typeof LawsLawIdRoute
  '/exam/': typeof ExamIndexRoute
  '/laws/': typeof LawsIndexRoute
  '/read/$lawId/$n': typeof ReadLawIdNRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/daily'
    | '/reminders'
    | '/search'
    | '/exam/quiz'
    | '/laws/$lawId'
    | '/exam/'
    | '/laws/'
    | '/read/$lawId/$n'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/daily'
    | '/reminders'
    | '/search'
    | '/exam/quiz'
    | '/laws/$lawId'
    | '/exam'
    | '/laws'
    | '/read/$lawId/$n'
  id:
    | '__root__'
    | '/'
    | '/daily'
    | '/reminders'
    | '/search'
    | '/exam/quiz'
    | '/laws/$lawId'
    | '/exam/'
    | '/laws/'
    | '/read/$lawId/$n'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DailyRoute: typeof DailyRoute
  RemindersRoute: typeof RemindersRoute
  SearchRoute: typeof SearchRoute
  ExamQuizRoute: typeof ExamQuizRoute
  LawsLawIdRoute: typeof LawsLawIdRoute
  ExamIndexRoute: typeof ExamIndexRoute
  LawsIndexRoute: typeof LawsIndexRoute
  ReadLawIdNRoute: typeof ReadLawIdNRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily': {
      id: '/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof DailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders': {
      id: '/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof RemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/': {
      id: '/exam/'
      path: '/exam'
      fullPath: '/exam/'
      preLoaderRoute: typeof ExamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/quiz': {
      id: '/exam/quiz'
      path: '/exam/quiz'
      fullPath: '/exam/quiz'
      preLoaderRoute: typeof ExamQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laws/': {
      id: '/laws/'
      path: '/laws'
      fullPath: '/laws/'
      preLoaderRoute: typeof LawsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laws/$lawId': {
      id: '/laws/$lawId'
      path: '/laws/$lawId'
      fullPath: '/laws/$lawId'
      preLoaderRoute: typeof LawsLawIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/$lawId/$n': {
      id: '/read/$lawId/$n'
      path: '/read/$lawId/$n'
      fullPath: '/read/$lawId/$n'
      preLoaderRoute: typeof ReadLawIdNRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DailyRoute: DailyRoute,
  RemindersRoute: RemindersRoute,
  SearchRoute: SearchRoute,
  ExamQuizRoute: ExamQuizRoute,
  LawsLawIdRoute: LawsLawIdRoute,
  ExamIndexRoute: ExamIndexRoute,
  LawsIndexRoute: LawsIndexRoute,
  ReadLawIdNRoute: ReadLawIdNRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
